### ISSUE TITLE
Hello :(

### ISSUE THREAD

**Issue by robert35** [ofeigenbaum/vue-cli-builder#1]
Hi, I'm working on an angular personal project and i did see your issue at https://github.com/angular/components/issues/26989
did you succeed in solving it ?
I have the same problem (on mac too)
Regards
jeanpaul.vallee1@gmail.com

Sorry for how i contact u, i don't have any other way to contact you.

**Comment by robert35** [comment]
ok it has finished after a long time, finally i don't get the problem anymore, sorry, c u 
:-)

**Comment by ofeigenbaum** [comment]
I am not quite sure anymore, but I can recommend that you use PNPM instead of NPM. Also, make sure you use a LTS Node/NPM Version. Finnaly run npm install with verbose flag so that you might get more info and output
